# Generated by Django 3.2.9 on 2021-12-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Fin de la Pobreza', 'Fin de la pobreza'), ('Hambre Cero', 'Hambre Cero'), ('Salud y Bienestar', 'Salud y Bienestar'), ('Educación de Calidad', 'Educación de Calidad'), ('Igualdad de Género', 'Igualdad de Género'), ('Agua limpia y Saneamiento', 'Agua limpia y Saneamiento'), ('Energía asequible y no contaminante', 'Energía asequible y no contaminante'), ('Agua, Industria,Innovacion e Infraestructura', 'Agua, Industria,Innovacion e Infraestructura'), ('Reducción de las Desigualdades', 'Reducción de las Desigualdades'), ('Ciudades Sostenibles', 'Ciudades Sostenibles'), ('Producción y Consumo Responsable', 'Producción y Consumo Responsable'), ('Acción por el Clima', 'Acción por el Clima'), ('Vida Sumbarina', 'Vida Submarina'), ('Vida de Ecosistemas Terrestres', 'Vida de Ecosistemas Terrestres'), ('Paz y Justicia', 'Paz y Justicia'), ('Alianzas para lograr los objetivos', 'Alianzas para lograr los objetivos')], default='sin categoria', max_length=120),
        ),
    ]
